"""Cover composition: red frame, white plate, headline — drawn locally.

Text on the image is never generated by a neural network. Image models mangle
Cyrillic into plausible-looking nonsense, and the headline is the one part of a
post a reader sees before deciding whether to read it at all.

The generated image is the background; the frame and plate go on top. That way a
cover still looks deliberate even when the underlying picture is mediocre.

Everything about the look lives in a JSON template inside the project directory,
so changing the design never means changing code.
"""

from __future__ import annotations

import io
import json
from functools import lru_cache
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from factory.core.errors import FactoryError

FONT_PATH = Path(__file__).resolve().parent / "fonts" / "NotoSans-Bold.ttf"

REQUIRED_SECTIONS = ("canvas", "frame", "plate", "title")


def parse_colour(value: str) -> tuple[int, int, int]:
    """``#RRGGBB`` into a tuple. Anything else is a config error, not a crash."""
    text = str(value).strip().lstrip("#")
    if len(text) != 6:
        raise FactoryError(
            f"Не удалось разобрать цвет: '{value}'.",
            why="Ожидается запись вида #RRGGBB, например #D32F2F.",
            what_to_do="Исправь цвет в шаблоне обложки.",
        )
    try:
        return tuple(int(text[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]
    except ValueError:
        raise FactoryError(
            f"Не удалось разобрать цвет: '{value}'.",
            why="В записи есть символы, не являющиеся шестнадцатеричными цифрами.",
            what_to_do="Допустимы только 0-9 и A-F, например #FFFFFF.",
        ) from None


def load_template(path: Path) -> dict:
    """Read and sanity-check a cover template."""
    if not Path(path).is_file():
        raise FactoryError(
            f"Шаблон обложки не найден: {path}",
            why="Файл указан в конфиге проекта в поле image.cover_template.",
            what_to_do="Проверь путь или скопируй шаблон из projects/demo/templates/.",
        )

    try:
        spec = json.loads(Path(path).read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise FactoryError(
            f"Шаблон обложки не читается: {path}",
            why=f"Ошибка разбора JSON: {exc}.",
            what_to_do="Чаще всего дело в лишней запятой или незакрытой скобке.",
        ) from exc

    missing = [name for name in REQUIRED_SECTIONS if name not in spec]
    if missing:
        raise FactoryError(
            f"В шаблоне обложки не хватает разделов: {', '.join(missing)}.",
            why=f"Файл: {path}",
            what_to_do="Сравни с projects/demo/templates/red_frame.json.",
        )

    canvas, plate = spec["canvas"], spec["plate"]
    fits = (
        plate["x"] >= 0
        and plate["y"] >= 0
        and plate["x"] + plate["width"] <= canvas["width"]
        and plate["y"] + plate["height"] <= canvas["height"]
    )
    if not fits:
        raise FactoryError(
            "Плашка не помещается в холст обложки.",
            why=(
                f"Плашка {plate['width']}×{plate['height']} в точке "
                f"({plate['x']}, {plate['y']}), холст "
                f"{canvas['width']}×{canvas['height']}."
            ),
            what_to_do=f"Поправь размеры в {path}.",
        )

    return spec


@lru_cache(maxsize=64)
def load_font(size: int) -> ImageFont.FreeTypeFont:
    """The bundled bold sans. Cached: fitting a size tries a dozen of them."""
    if not FONT_PATH.is_file():
        raise FactoryError(
            f"Шрифт для обложки не найден: {FONT_PATH}",
            why="Файл шрифта должен лежать в репозитории и попадать в образ.",
            what_to_do="Восстанови factory/compose/fonts/ из репозитория.",
        )
    return ImageFont.truetype(str(FONT_PATH), size)


def wrap(text: str, font: ImageFont.FreeTypeFont, available_width: int) -> list[str]:
    """Break a headline into lines without splitting words.

    A word longer than the line stays whole and overflows: breaking Russian words
    mid-stem looks like a typo, and the size fitting below will shrink the text
    until it fits anyway.
    """
    words = text.split()
    if not words:
        return []

    lines: list[str] = []
    current = words[0]

    for word in words[1:]:
        candidate = f"{current} {word}"
        if font.getbbox(candidate)[2] <= available_width:
            current = candidate
        else:
            lines.append(current)
            current = word

    lines.append(current)
    return lines


def _block_size(lines: list[str], font: ImageFont.FreeTypeFont, spacing: float) -> tuple[int, int]:
    if not lines:
        return 0, 0
    widths = [font.getbbox(line)[2] for line in lines]
    line_height = font.getbbox("Ёg")[3]
    height = int(line_height * spacing * (len(lines) - 1) + line_height)
    return max(widths), height


def fit_font_size(text: str, spec: dict) -> int:
    """Largest size from the template's range at which the headline still fits.

    Tried from the top down: a headline should be as large as the plate allows,
    and only shrink when it has to.
    """
    title = spec["title"]
    plate = spec["plate"]
    padding = plate["padding"]
    available_width = plate["width"] - 2 * padding
    available_height = plate["height"] - 2 * padding
    spacing = title.get("line_spacing", 1.1)

    low, high = int(title["size_min"]), int(title["size_max"])

    for size in range(high, low - 1, -1):
        font = load_font(size)
        width, height = _block_size(wrap(text, font, available_width), font, spacing)
        if width <= available_width and height <= available_height:
            return size

    return low


def text_bounds(image: Image.Image, colour: tuple[int, int, int]) -> tuple[int, int, int, int] | None:
    """Bounding box of pixels close to ``colour``. Used by tests to prove fit."""
    rgb = image.convert("RGB")
    width, height = rgb.size
    pixels = rgb.load()

    left, top, right, bottom = width, height, -1, -1
    for y in range(height):
        for x in range(width):
            pixel = pixels[x, y]
            if all(abs(pixel[i] - colour[i]) < 40 for i in range(3)):
                left, top = min(left, x), min(top, y)
                right, bottom = max(right, x), max(bottom, y)

    return None if right < 0 else (left, top, right, bottom)


def render(background: bytes, title: str, template_path: Path) -> bytes:
    """Compose the cover. Returns PNG bytes.

    Deterministic: the same background, headline and template always produce
    identical bytes, so re-running the step never rewrites the file with a
    different one.
    """
    spec = load_template(Path(template_path))
    canvas = spec["canvas"]
    frame = spec["frame"]
    plate = spec["plate"]
    title_spec = spec["title"]

    size = (int(canvas["width"]), int(canvas["height"]))

    try:
        image = Image.open(io.BytesIO(background)).convert("RGB")
    except OSError as exc:
        raise FactoryError(
            "Фоновая картинка обложки не читается.",
            why=f"Pillow не смог её открыть: {exc}.",
            what_to_do="Перезапусти пост, чтобы картинка сгенерировалась заново.",
        ) from exc

    if image.size != size:
        image = image.resize(size, Image.LANCZOS)

    draw = ImageDraw.Draw(image)

    thickness = int(frame["width_px"])
    frame_colour = parse_colour(frame["color"])
    for offset in range(thickness):
        draw.rectangle(
            [offset, offset, size[0] - 1 - offset, size[1] - 1 - offset],
            outline=frame_colour,
        )

    draw.rectangle(
        [plate["x"], plate["y"], plate["x"] + plate["width"], plate["y"] + plate["height"]],
        fill=parse_colour(plate["color"]),
    )

    if title.strip():
        padding = plate["padding"]
        available_width = plate["width"] - 2 * padding
        spacing = title_spec.get("line_spacing", 1.1)

        font = load_font(fit_font_size(title, spec))
        lines = wrap(title, font, available_width)
        line_height = font.getbbox("Ёg")[3]
        _, block_height = _block_size(lines, font, spacing)

        y = plate["y"] + padding
        if title_spec.get("valign", "center") == "center":
            y = plate["y"] + (plate["height"] - block_height) // 2

        colour = parse_colour(title_spec["color"])
        for line in lines:
            draw.text((plate["x"] + padding, y), line, font=font, fill=colour)
            y += int(line_height * spacing)

    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()
